apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshjump
  namespace: haproxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sshjump
  template:
    metadata:
      labels:
        app: sshjump
    spec:
      automountServiceAccountToken: true
      containers:
      - image: clysec/sshjump:latest
        imagePullPolicy: Always
        name: sshjump
        ports:
        - containerPort: 2222
          name: ssh
          protocol: TCP
        resources: {}
        envFrom:
        - configMapRef:
            name: sshjump-config
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
