name: Build and Publish Packages

on:
  push:
    tags: ["*.*.*"]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.3
      id: go
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Fetch signer
      run: |
        wget https://static.cloudyne.io/signer-linux-amd64
        chmod +x signer-linux-amd64
        sudo mv signer-linux-amd64 /usr/local/bin/signer

    - name: Goreleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_DEBPKG_SECRET: ${{ secrets.GITEA_TOKEN }}
        UPLOAD_APKPKG_SECRET: ${{ secrets.GITEA_TOKEN }}
        UPLOAD_RPMPKG_SECRET: ${{ secrets.GITEA_TOKEN }}
        UPLOAD_DEBPKG_USER: ${{ secrets.GITEA_USER }}
        OSCS_AKV_URL: ${{ secrets.OSCS_AKV_URL }}
        OSCS_AKV_CERT: ${{ secrets.OSCS_AKV_CERT }}
        OSCS_AKV_CERT_VERSION: ${{ secrets.OSCS_AKV_CERT_VERSION }}
        OSCS_AKV_TENANT: ${{ secrets.OSCS_AKV_TENANT }}
        OSCS_AKV_CLIENT: ${{ secrets.OSCS_AKV_CLIENT }}
        OSCS_AKV_SECRET: ${{ secrets.OSCS_AKV_SECRET }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist/**
